mv data/combined/LibPlate10-combined_RA_GGACAAGCTATGCAGG.fastq data/align/3103-499_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAACAACCATGCAGG.fastq data/align/3103-507_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGATCGCATGCAGG.fastq data/align/3103-515_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCGAAGTATGCAGG.fastq data/align/3103-523_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGATAGACATGCAGG.fastq data/align/3103-484_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTATCAGCATGCAGG.fastq data/align/3103-492_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAATGTTGCTGCAGG.fastq data/align/3103-500_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCATCCTCTGCAGG.fastq data/align/3103-508_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAAACATCGTGCAGG.fastq data/align/3103-516_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAACCGAGATGCAGG.fastq data/align/3103-524_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGCAGGAATGCAGG.fastq data/align/3103-485_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCGTGAGATGCAGG.fastq data/align/3103-493_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGCCACATATGCAGG.fastq data/align/3103-501_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTCCGTCTATGCAGG.fastq data/align/3103-509_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACACTGACTGCAGG.fastq data/align/3103-517_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCGACAACTGCAGG.fastq data/align/3103-525_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACATTGGCTGCAGG.fastq data/align/3103-486_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAACGCTTATGCAGG.fastq data/align/3103-494_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGTCACTATGCAGG.fastq data/align/3103-502_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCTCCTGATGCAGG.fastq data/align/3103-510_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGCGAGTAATGCAGG.fastq data/align/3103-518_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTCTTCACATGCAGG.fastq data/align/3103-526_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACAGATTCTGCAGG.fastq data/align/3103-487_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGTCAAGCTGCAGG.fastq data/align/3103-495_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACCACTGTTGCAGG.fastq data/align/3103-503_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAAGACGGATGCAGG.fastq data/align/3103-511_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGATCCTGTATGCAGG.fastq data/align/3103-519_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGAACTTATGCAGG.fastq data/align/3103-527_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGCTAACGATGCAGG.fastq data/align/3103-488_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTGAAGAGATGCAGG.fastq data/align/3103-496_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGATGTACTGCAGG.fastq data/align/3103-504_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCTCTATCTGCAGG.fastq data/align/3103-512_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAACGTGATTGCAGG.fastq data/align/3103-520_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAAGGTACATGCAGG.fastq data/align/3103-528_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGATTGAGGATGCAGG.fastq data/align/3103-577_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGACTGGATGCAGG.fastq data/align/3103-578_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGCTCGGTATGCAGG.fastq data/align/3103-579_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTGGAACAATGCAGG.fastq data/align/3103-580_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGCACCTCTGCAGG.fastq data/align/3103-581_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGACACACTGCAGG.fastq data/align/3103-582_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGCTGATCTGCAGG.fastq data/align/3103-585_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACACAGAATGCAGG.fastq data/align/3103-586_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAACCACATGCAGG.fastq data/align/3103-587_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGCATACATGCAGG.fastq data/align/3103-588_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGGAGAACATGCAGG.fastq data/align/3103-589_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTGGCTTCATGCAGG.fastq data/align/3103-590_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGCCATGCTGCAGG.fastq data/align/3103-591_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCGGATTGCTGCAGG.fastq data/align/3103-592_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAGATCTGTGCAGG.fastq data/align/3103-593_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACAGCAGATGCAGG.fastq data/align/3103-594_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAAGACTATGCAGG.fastq data/align/3103-595_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCTCAATGATGCAGG.fastq data/align/3103-596_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGGTGCGAATGCAGG.fastq data/align/3103-597_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTGGTGGTATGCAGG.fastq data/align/3103-598_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGGCTAACTGCAGG.fastq data/align/3103-599_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCTAAGGTCTGCAGG.fastq data/align/3103-600_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGATGCCTAATGCAGG.fastq data/align/3103-601_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACCTCCAATGCAGG.fastq data/align/3103-602_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAATGGAATGCAGG.fastq data/align/3103-603_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCTGAGCCATGCAGG.fastq data/align/3103-604_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGTACGCAATGCAGG.fastq data/align/3103-605_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTTCACGCATGCAGG.fastq data/align/3103-606_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGATAGCGACTGCAGG.fastq data/align/3103-607_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGAACAGGCTGCAGG.fastq data/align/3103-608_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAACGAACGTGCAGG.fastq data/align/3103-609_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACGCTCGATGCAGG.fastq data/align/3103-610_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCACTTCGATGCAGG.fastq data/align/3103-611_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCTGGCATATGCAGG.fastq data/align/3103-612_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGTCGTAGATGCAGG.fastq data/align/3103-613_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACACGAGATGCAGG.fastq data/align/3103-614_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACGACAAGTGCAGG.fastq data/align/3103-615_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGACAGTGCTGCAGG.fastq data/align/3103-616_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGTACAAGTGCAGG.fastq data/align/3103-617_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACGTATCATGCAGG.fastq data/align/3103-618_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAGCGTTATGCAGG.fastq data/align/3103-619_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGAATCTGATGCAGG.fastq data/align/3103-620_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGTCTGTCATGCAGG.fastq data/align/3103-621_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAAGAGATCTGCAGG.fastq data/align/3103-622_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGATTGGCTCTGCAGG.fastq data/align/3103-623_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGAGTTAGCTGCAGG.fastq data/align/3103-624_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCATCAAGTTGCAGG.fastq data/align/3103-583_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGACTATGCATGCAGG.fastq data/align/3103-584_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCATACCAATGCAGG.fastq data/align/3103-673_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGACTAGTATGCAGG.fastq data/align/3103-674_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGTGTTCTATGCAGG.fastq data/align/3103-675_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAAGGACACTGCAGG.fastq data/align/3103-676_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCAAGGAGCTGCAGG.fastq data/align/3103-677_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGATGAATCTGCAGG.fastq data/align/3103-678_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGTGGTCATGCAGG.fastq data/align/3103-679_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAGAGTCAATGCAGG.fastq data/align/3103-681_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCCAGTTCATGCAGG.fastq data/align/3103-682_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGAGCTGAATGCAGG.fastq data/align/3103-683_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGTAGGATGATGCAGG.fastq data/align/3103-684_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGAATCCGTCTGCAGG.fastq data/align/3103-685_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGCACCTTACTGCAGG.fastq data/align/3103-686_RA.fastq
mv data/combined/LibPlate10-combined_RA_GGGCCAAGACTGCAGG.fastq data/align/3103-689_RA.fastq
mv data/combined/LibPlate10-combined_RB_GGACAAGCTATGCAGG.fastq data/align/3103-499_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAACAACCATGCAGG.fastq data/align/3103-507_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGATCGCATGCAGG.fastq data/align/3103-515_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCGAAGTATGCAGG.fastq data/align/3103-523_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGATAGACATGCAGG.fastq data/align/3103-484_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTATCAGCATGCAGG.fastq data/align/3103-492_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAATGTTGCTGCAGG.fastq data/align/3103-500_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCATCCTCTGCAGG.fastq data/align/3103-508_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAAACATCGTGCAGG.fastq data/align/3103-516_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAACCGAGATGCAGG.fastq data/align/3103-524_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGCAGGAATGCAGG.fastq data/align/3103-485_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCGTGAGATGCAGG.fastq data/align/3103-493_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGCCACATATGCAGG.fastq data/align/3103-501_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTCCGTCTATGCAGG.fastq data/align/3103-509_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACACTGACTGCAGG.fastq data/align/3103-517_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCGACAACTGCAGG.fastq data/align/3103-525_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACATTGGCTGCAGG.fastq data/align/3103-486_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAACGCTTATGCAGG.fastq data/align/3103-494_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGTCACTATGCAGG.fastq data/align/3103-502_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCTCCTGATGCAGG.fastq data/align/3103-510_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGCGAGTAATGCAGG.fastq data/align/3103-518_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTCTTCACATGCAGG.fastq data/align/3103-526_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACAGATTCTGCAGG.fastq data/align/3103-487_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGTCAAGCTGCAGG.fastq data/align/3103-495_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACCACTGTTGCAGG.fastq data/align/3103-503_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAAGACGGATGCAGG.fastq data/align/3103-511_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGATCCTGTATGCAGG.fastq data/align/3103-519_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGAACTTATGCAGG.fastq data/align/3103-527_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGCTAACGATGCAGG.fastq data/align/3103-488_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTGAAGAGATGCAGG.fastq data/align/3103-496_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGATGTACTGCAGG.fastq data/align/3103-504_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCTCTATCTGCAGG.fastq data/align/3103-512_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAACGTGATTGCAGG.fastq data/align/3103-520_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAAGGTACATGCAGG.fastq data/align/3103-528_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGATTGAGGATGCAGG.fastq data/align/3103-577_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGACTGGATGCAGG.fastq data/align/3103-578_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGCTCGGTATGCAGG.fastq data/align/3103-579_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTGGAACAATGCAGG.fastq data/align/3103-580_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGCACCTCTGCAGG.fastq data/align/3103-581_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGACACACTGCAGG.fastq data/align/3103-582_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGCTGATCTGCAGG.fastq data/align/3103-585_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACACAGAATGCAGG.fastq data/align/3103-586_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAACCACATGCAGG.fastq data/align/3103-587_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGCATACATGCAGG.fastq data/align/3103-588_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGGAGAACATGCAGG.fastq data/align/3103-589_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTGGCTTCATGCAGG.fastq data/align/3103-590_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGCCATGCTGCAGG.fastq data/align/3103-591_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCGGATTGCTGCAGG.fastq data/align/3103-592_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAGATCTGTGCAGG.fastq data/align/3103-593_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACAGCAGATGCAGG.fastq data/align/3103-594_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAAGACTATGCAGG.fastq data/align/3103-595_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCTCAATGATGCAGG.fastq data/align/3103-596_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGGTGCGAATGCAGG.fastq data/align/3103-597_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTGGTGGTATGCAGG.fastq data/align/3103-598_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGGCTAACTGCAGG.fastq data/align/3103-599_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCTAAGGTCTGCAGG.fastq data/align/3103-600_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGATGCCTAATGCAGG.fastq data/align/3103-601_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACCTCCAATGCAGG.fastq data/align/3103-602_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAATGGAATGCAGG.fastq data/align/3103-603_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCTGAGCCATGCAGG.fastq data/align/3103-604_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGTACGCAATGCAGG.fastq data/align/3103-605_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTTCACGCATGCAGG.fastq data/align/3103-606_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGATAGCGACTGCAGG.fastq data/align/3103-607_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGAACAGGCTGCAGG.fastq data/align/3103-608_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAACGAACGTGCAGG.fastq data/align/3103-609_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACGCTCGATGCAGG.fastq data/align/3103-610_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCACTTCGATGCAGG.fastq data/align/3103-611_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCTGGCATATGCAGG.fastq data/align/3103-612_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGTCGTAGATGCAGG.fastq data/align/3103-613_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACACGAGATGCAGG.fastq data/align/3103-614_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACGACAAGTGCAGG.fastq data/align/3103-615_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGACAGTGCTGCAGG.fastq data/align/3103-616_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGTACAAGTGCAGG.fastq data/align/3103-617_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACGTATCATGCAGG.fastq data/align/3103-618_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAGCGTTATGCAGG.fastq data/align/3103-619_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGAATCTGATGCAGG.fastq data/align/3103-620_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGTCTGTCATGCAGG.fastq data/align/3103-621_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAAGAGATCTGCAGG.fastq data/align/3103-622_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGATTGGCTCTGCAGG.fastq data/align/3103-623_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGAGTTAGCTGCAGG.fastq data/align/3103-624_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCATCAAGTTGCAGG.fastq data/align/3103-583_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGACTATGCATGCAGG.fastq data/align/3103-584_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCATACCAATGCAGG.fastq data/align/3103-673_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGACTAGTATGCAGG.fastq data/align/3103-674_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGTGTTCTATGCAGG.fastq data/align/3103-675_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAAGGACACTGCAGG.fastq data/align/3103-676_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCAAGGAGCTGCAGG.fastq data/align/3103-677_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGATGAATCTGCAGG.fastq data/align/3103-678_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGTGGTCATGCAGG.fastq data/align/3103-679_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAGAGTCAATGCAGG.fastq data/align/3103-681_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCCAGTTCATGCAGG.fastq data/align/3103-682_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGAGCTGAATGCAGG.fastq data/align/3103-683_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGTAGGATGATGCAGG.fastq data/align/3103-684_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGAATCCGTCTGCAGG.fastq data/align/3103-685_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGCACCTTACTGCAGG.fastq data/align/3103-686_RB.fastq
mv data/combined/LibPlate10-combined_RB_GGGCCAAGACTGCAGG.fastq data/align/3103-689_RB.fastq
