mv data/combined/RAP1-combined_RA_GGACAAGCTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_001_RA.fastq
mv data/combined/RAP1-combined_RA_GGAAACATCGTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_009_RA.fastq
mv data/combined/RAP1-combined_RA_GGACATTGGCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_017_RA.fastq
mv data/combined/RAP1-combined_RA_GGACCACTGTTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_025_RA.fastq
mv data/combined/RAP1-combined_RA_GGAACGTGATTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_008_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGCTGATCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_018_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAGATCTGTGCAGG.fastq data/alignRAP1/QUI_AND_2016_002_RA.fastq
mv data/combined/RAP1-combined_RA_GGATGCCTAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_003_RA.fastq
mv data/combined/RAP1-combined_RA_GGAACGAACGTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_120_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGTACAAGTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_052_RA.fastq
mv data/combined/RAP1-combined_RA_GGCATCAAGTTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_060_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGTGGTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_066_RA.fastq
mv data/combined/RAP1-combined_RA_GGAACAACCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_002_RA.fastq
mv data/combined/RAP1-combined_RA_GGAACCGAGATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_010_RA.fastq
mv data/combined/RAP1-combined_RA_GGAACGCTTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_018_RA.fastq
mv data/combined/RAP1-combined_RA_GGAAGACGGATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_026_RA.fastq
mv data/combined/RAP1-combined_RA_GGAAGGTACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_009_RA.fastq
mv data/combined/RAP1-combined_RA_GGACACAGAATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_111_RA.fastq
mv data/combined/RAP1-combined_RA_GGACAGCAGATGCAGG.fastq data/alignRAP1/QUI_AND_2016_003_RA.fastq
mv data/combined/RAP1-combined_RA_GGACCTCCAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_004_RA.fastq
mv data/combined/RAP1-combined_RA_GGACGCTCGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_121_RA.fastq
mv data/combined/RAP1-combined_RA_GGACGTATCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_053_RA.fastq
mv data/combined/RAP1-combined_RA_GGACTATGCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_061_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGAGTCAATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_067_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGATCGCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_003_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGCAGGAATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_011_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGTCACTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_019_RA.fastq
mv data/combined/RAP1-combined_RA_GGATCCTGTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_027_RA.fastq
mv data/combined/RAP1-combined_RA_GGATTGAGGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_010_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAACCACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_222_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAAGACTATGCAGG.fastq data/alignRAP1/QUI_AND_2016_004_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAATGGAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_005_RA.fastq
mv data/combined/RAP1-combined_RA_GGCACTTCGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_122_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAGCGTTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_054_RA.fastq
mv data/combined/RAP1-combined_RA_GGCATACCAATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_062_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCAGTTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_068_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCGAAGTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_004_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCGTGAGATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_012_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCTCCTGATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_020_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGAACTTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_028_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGACTGGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_011_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGCATACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_333_RA.fastq
mv data/combined/RAP1-combined_RA_GGCTCAATGATGCAGG.fastq data/alignRAP1/QUI_AND_2016_005_RA.fastq
mv data/combined/RAP1-combined_RA_GGCTGAGCCATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_006_RA.fastq
mv data/combined/RAP1-combined_RA_GGCTGGCATATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_123_RA.fastq
mv data/combined/RAP1-combined_RA_GGGAATCTGATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_055_RA.fastq
mv data/combined/RAP1-combined_RA_GGGACTAGTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_063_RA.fastq
mv data/combined/RAP1-combined_RA_GGGAGCTGAATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_069_RA.fastq
mv data/combined/RAP1-combined_RA_GGGATAGACATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_005_RA.fastq
mv data/combined/RAP1-combined_RA_GGGCCACATATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_013_RA.fastq
mv data/combined/RAP1-combined_RA_GGGCGAGTAATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_021_RA.fastq
mv data/combined/RAP1-combined_RA_GGGCTAACGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_001_RA.fastq
mv data/combined/RAP1-combined_RA_GGGCTCGGTATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_012_RA.fastq
mv data/combined/RAP1-combined_RA_GGGGAGAACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_444_RA.fastq
mv data/combined/RAP1-combined_RA_GGGGTGCGAATGCAGG.fastq data/alignRAP1/QUI_AND_2016_006_RA.fastq
mv data/combined/RAP1-combined_RA_GGGTACGCAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_007_RA.fastq
mv data/combined/RAP1-combined_RA_GGGTCGTAGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_124_RA.fastq
mv data/combined/RAP1-combined_RA_GGGTCTGTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_056_RA.fastq
mv data/combined/RAP1-combined_RA_GGGTGTTCTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_064_RA.fastq
mv data/combined/RAP1-combined_RA_GGTAGGATGATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_071_RA.fastq
mv data/combined/RAP1-combined_RA_GGTATCAGCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_006_RA.fastq
mv data/combined/RAP1-combined_RA_GGTCCGTCTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_014_RA.fastq
mv data/combined/RAP1-combined_RA_GGTCTTCACATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_022_RA.fastq
mv data/combined/RAP1-combined_RA_GGTGAAGAGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_002_RA.fastq
mv data/combined/RAP1-combined_RA_GGTGGAACAATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_014_RA.fastq
mv data/combined/RAP1-combined_RA_GGTGGCTTCATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_555_RA.fastq
mv data/combined/RAP1-combined_RA_GGTGGTGGTATGCAGG.fastq data/alignRAP1/QUI_AND_2016_111_RA.fastq
mv data/combined/RAP1-combined_RA_GGTTCACGCATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_117_RA.fastq
mv data/combined/RAP1-combined_RA_GGACACGAGATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_049_RA.fastq
mv data/combined/RAP1-combined_RA_GGAAGAGATCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_057_RA.fastq
mv data/combined/RAP1-combined_RA_GGAAGGACACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_062_RA.fastq
mv data/combined/RAP1-combined_RA_GGAATCCGTCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_072_RA.fastq
mv data/combined/RAP1-combined_RA_GGAATGTTGCTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_007_RA.fastq
mv data/combined/RAP1-combined_RA_GGACACTGACTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_015_RA.fastq
mv data/combined/RAP1-combined_RA_GGACAGATTCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_023_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGATGTACTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_003_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGCACCTCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_015_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGCCATGCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_666_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGGCTAACTGCAGG.fastq data/alignRAP1/QUI_NFB_2016_001_RA.fastq
mv data/combined/RAP1-combined_RA_GGATAGCGACTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_118_RA.fastq
mv data/combined/RAP1-combined_RA_GGACGACAAGTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_050_RA.fastq
mv data/combined/RAP1-combined_RA_GGATTGGCTCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_058_RA.fastq
mv data/combined/RAP1-combined_RA_GGCAAGGAGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_063_RA.fastq
mv data/combined/RAP1-combined_RA_GGCACCTTACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_074_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCATCCTCTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_008_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCGACAACTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_016_RA.fastq
mv data/combined/RAP1-combined_RA_GGAGTCAAGCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_024_RA.fastq
mv data/combined/RAP1-combined_RA_GGCCTCTATCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_005_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGACACACTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_017_RA.fastq
mv data/combined/RAP1-combined_RA_GGCGGATTGCTGCAGG.fastq data/alignRAP1/QUI_AND_2016_001_RA.fastq
mv data/combined/RAP1-combined_RA_GGCTAAGGTCTGCAGG.fastq data/alignRAP1/QUI_NFB_2016_002_RA.fastq
mv data/combined/RAP1-combined_RA_GGGAACAGGCTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_119_RA.fastq
mv data/combined/RAP1-combined_RA_GGGACAGTGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_051_RA.fastq
mv data/combined/RAP1-combined_RA_GGGAGTTAGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_059_RA.fastq
mv data/combined/RAP1-combined_RA_GGGATGAATCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_064_RA.fastq
mv data/combined/RAP1-combined_RA_GGGCCAAGACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_075_RA.fastq
mv data/combined/RAP1-combined_RB_GGACAAGCTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_001_RB.fastq
mv data/combined/RAP1-combined_RB_GGAAACATCGTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_009_RB.fastq
mv data/combined/RAP1-combined_RB_GGACATTGGCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_017_RB.fastq
mv data/combined/RAP1-combined_RB_GGACCACTGTTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_025_RB.fastq
mv data/combined/RAP1-combined_RB_GGAACGTGATTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_008_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGCTGATCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_018_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAGATCTGTGCAGG.fastq data/alignRAP1/QUI_AND_2016_002_RB.fastq
mv data/combined/RAP1-combined_RB_GGATGCCTAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_003_RB.fastq
mv data/combined/RAP1-combined_RB_GGAACGAACGTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_120_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGTACAAGTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_052_RB.fastq
mv data/combined/RAP1-combined_RB_GGCATCAAGTTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_060_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGTGGTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_066_RB.fastq
mv data/combined/RAP1-combined_RB_GGAACAACCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_002_RB.fastq
mv data/combined/RAP1-combined_RB_GGAACCGAGATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_010_RB.fastq
mv data/combined/RAP1-combined_RB_GGAACGCTTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_018_RB.fastq
mv data/combined/RAP1-combined_RB_GGAAGACGGATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_026_RB.fastq
mv data/combined/RAP1-combined_RB_GGAAGGTACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_009_RB.fastq
mv data/combined/RAP1-combined_RB_GGACACAGAATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_111_RB.fastq
mv data/combined/RAP1-combined_RB_GGACAGCAGATGCAGG.fastq data/alignRAP1/QUI_AND_2016_003_RB.fastq
mv data/combined/RAP1-combined_RB_GGACCTCCAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_004_RB.fastq
mv data/combined/RAP1-combined_RB_GGACGCTCGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_121_RB.fastq
mv data/combined/RAP1-combined_RB_GGACGTATCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_053_RB.fastq
mv data/combined/RAP1-combined_RB_GGACTATGCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_061_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGAGTCAATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_067_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGATCGCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_003_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGCAGGAATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_011_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGTCACTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_019_RB.fastq
mv data/combined/RAP1-combined_RB_GGATCCTGTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_027_RB.fastq
mv data/combined/RAP1-combined_RB_GGATTGAGGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_010_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAACCACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_222_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAAGACTATGCAGG.fastq data/alignRAP1/QUI_AND_2016_004_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAATGGAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_005_RB.fastq
mv data/combined/RAP1-combined_RB_GGCACTTCGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_122_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAGCGTTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_054_RB.fastq
mv data/combined/RAP1-combined_RB_GGCATACCAATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_062_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCAGTTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_068_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCGAAGTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_004_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCGTGAGATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_012_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCTCCTGATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_020_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGAACTTATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_028_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGACTGGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_011_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGCATACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_333_RB.fastq
mv data/combined/RAP1-combined_RB_GGCTCAATGATGCAGG.fastq data/alignRAP1/QUI_AND_2016_005_RB.fastq
mv data/combined/RAP1-combined_RB_GGCTGAGCCATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_006_RB.fastq
mv data/combined/RAP1-combined_RB_GGCTGGCATATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_123_RB.fastq
mv data/combined/RAP1-combined_RB_GGGAATCTGATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_055_RB.fastq
mv data/combined/RAP1-combined_RB_GGGACTAGTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_063_RB.fastq
mv data/combined/RAP1-combined_RB_GGGAGCTGAATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_069_RB.fastq
mv data/combined/RAP1-combined_RB_GGGATAGACATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_005_RB.fastq
mv data/combined/RAP1-combined_RB_GGGCCACATATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_013_RB.fastq
mv data/combined/RAP1-combined_RB_GGGCGAGTAATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_021_RB.fastq
mv data/combined/RAP1-combined_RB_GGGCTAACGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_001_RB.fastq
mv data/combined/RAP1-combined_RB_GGGCTCGGTATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_012_RB.fastq
mv data/combined/RAP1-combined_RB_GGGGAGAACATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_444_RB.fastq
mv data/combined/RAP1-combined_RB_GGGGTGCGAATGCAGG.fastq data/alignRAP1/QUI_AND_2016_006_RB.fastq
mv data/combined/RAP1-combined_RB_GGGTACGCAATGCAGG.fastq data/alignRAP1/QUI_NFB_2016_007_RB.fastq
mv data/combined/RAP1-combined_RB_GGGTCGTAGATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_124_RB.fastq
mv data/combined/RAP1-combined_RB_GGGTCTGTCATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_056_RB.fastq
mv data/combined/RAP1-combined_RB_GGGTGTTCTATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_064_RB.fastq
mv data/combined/RAP1-combined_RB_GGTAGGATGATGCAGG.fastq data/alignRAP1/MAG_BEA_2015_071_RB.fastq
mv data/combined/RAP1-combined_RB_GGTATCAGCATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_006_RB.fastq
mv data/combined/RAP1-combined_RB_GGTCCGTCTATGCAGG.fastq data/alignRAP1/SFH_2BO_2016_014_RB.fastq
mv data/combined/RAP1-combined_RB_GGTCTTCACATGCAGG.fastq data/alignRAP1/SFH_4BO_2016_022_RB.fastq
mv data/combined/RAP1-combined_RB_GGTGAAGAGATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_002_RB.fastq
mv data/combined/RAP1-combined_RB_GGTGGAACAATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_014_RB.fastq
mv data/combined/RAP1-combined_RB_GGTGGCTTCATGCAGG.fastq data/alignRAP1/LHU_ABE_2016_555_RB.fastq
mv data/combined/RAP1-combined_RB_GGTGGTGGTATGCAGG.fastq data/alignRAP1/QUI_AND_2016_111_RB.fastq
mv data/combined/RAP1-combined_RB_GGTTCACGCATGCAGG.fastq data/alignRAP1/QUI_BAT_2013_117_RB.fastq
mv data/combined/RAP1-combined_RB_GGACACGAGATGCAGG.fastq data/alignRAP1/MAG_BEA_2009_049_RB.fastq
mv data/combined/RAP1-combined_RB_GGAAGAGATCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_057_RB.fastq
mv data/combined/RAP1-combined_RB_GGAAGGACACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_062_RB.fastq
mv data/combined/RAP1-combined_RB_GGAATCCGTCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_072_RB.fastq
mv data/combined/RAP1-combined_RB_GGAATGTTGCTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_007_RB.fastq
mv data/combined/RAP1-combined_RB_GGACACTGACTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_015_RB.fastq
mv data/combined/RAP1-combined_RB_GGACAGATTCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_023_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGATGTACTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_003_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGCACCTCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_015_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGCCATGCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_666_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGGCTAACTGCAGG.fastq data/alignRAP1/QUI_NFB_2016_001_RB.fastq
mv data/combined/RAP1-combined_RB_GGATAGCGACTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_118_RB.fastq
mv data/combined/RAP1-combined_RB_GGACGACAAGTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_050_RB.fastq
mv data/combined/RAP1-combined_RB_GGATTGGCTCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_058_RB.fastq
mv data/combined/RAP1-combined_RB_GGCAAGGAGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_063_RB.fastq
mv data/combined/RAP1-combined_RB_GGCACCTTACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_074_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCATCCTCTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_008_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCGACAACTGCAGG.fastq data/alignRAP1/SFH_2BO_2016_016_RB.fastq
mv data/combined/RAP1-combined_RB_GGAGTCAAGCTGCAGG.fastq data/alignRAP1/SFH_4BO_2016_024_RB.fastq
mv data/combined/RAP1-combined_RB_GGCCTCTATCTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_005_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGACACACTGCAGG.fastq data/alignRAP1/LHU_ABE_2016_017_RB.fastq
mv data/combined/RAP1-combined_RB_GGCGGATTGCTGCAGG.fastq data/alignRAP1/QUI_AND_2016_001_RB.fastq
mv data/combined/RAP1-combined_RB_GGCTAAGGTCTGCAGG.fastq data/alignRAP1/QUI_NFB_2016_002_RB.fastq
mv data/combined/RAP1-combined_RB_GGGAACAGGCTGCAGG.fastq data/alignRAP1/QUI_BAT_2013_119_RB.fastq
mv data/combined/RAP1-combined_RB_GGGACAGTGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_051_RB.fastq
mv data/combined/RAP1-combined_RB_GGGAGTTAGCTGCAGG.fastq data/alignRAP1/MAG_BEA_2009_059_RB.fastq
mv data/combined/RAP1-combined_RB_GGGATGAATCTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_064_RB.fastq
mv data/combined/RAP1-combined_RB_GGGCCAAGACTGCAGG.fastq data/alignRAP1/MAG_BEA_2015_075_RB.fastq
