 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACAAGCTATGCAGG data/dummy/Omy-001
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAACAACCATGCAGG data/dummy/Omy-002
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGATCGCATGCAGG data/dummy/Omy-003
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCGAAGTATGCAGG data/dummy/Omy-004
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGATAGACATGCAGG data/dummy/Omy-006
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTATCAGCATGCAGG data/dummy/Omy-008
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAATGTTGCTGCAGG data/dummy/Omy-009
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCATCCTCTGCAGG data/dummy/Omy-010
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAAACATCGTGCAGG data/dummy/Omy-012
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAACCGAGATGCAGG data/dummy/Omy-013
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGCAGGAATGCAGG data/dummy/Omy-014
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCGTGAGATGCAGG data/dummy/Omy-015
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGCCACATATGCAGG data/dummy/Omy-016
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTCCGTCTATGCAGG data/dummy/Omy-017
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACACTGACTGCAGG data/dummy/Omy-018
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCGACAACTGCAGG data/dummy/Omy-019
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACATTGGCTGCAGG data/dummy/Omy-011
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAACGCTTATGCAGG data/dummy/Omy-020
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGTCACTATGCAGG data/dummy/Omy-021
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCTCCTGATGCAGG data/dummy/Omy-022
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGCGAGTAATGCAGG data/dummy/Omy-023
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTCTTCACATGCAGG data/dummy/Omy-024
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACAGATTCTGCAGG data/dummy/Omy-025
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGTCAAGCTGCAGG data/dummy/Omy-026
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACCACTGTTGCAGG data/dummy/Omy-027
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAAGACGGATGCAGG data/dummy/Omy-028
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGATCCTGTATGCAGG data/dummy/Omy-029
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGAACTTATGCAGG data/dummy/Omy-030
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGCTAACGATGCAGG data/dummy/Omy-031
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTGAAGAGATGCAGG data/dummy/Omy-032
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGATGTACTGCAGG data/dummy/Omy-033
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCTCTATCTGCAGG data/dummy/Omy-034
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAACGTGATTGCAGG data/dummy/Omy-035
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAAGGTACATGCAGG data/dummy/Omy-036
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGATTGAGGATGCAGG data/dummy/Omy-037
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGACTGGATGCAGG data/dummy/Omy-038
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGCTCGGTATGCAGG data/dummy/Omy-039
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTGGAACAATGCAGG data/dummy/Omy-040
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGCACCTCTGCAGG data/dummy/Omy-041
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGACACACTGCAGG data/dummy/Omy-042
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGCTGATCTGCAGG data/dummy/Omy-043
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACACAGAATGCAGG data/dummy/Omy-044
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAACCACATGCAGG data/dummy/Omy-045
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGCATACATGCAGG data/dummy/Omy-046
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGGAGAACATGCAGG data/dummy/Omy-047
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTGGCTTCATGCAGG data/dummy/Omy-048
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGCCATGCTGCAGG data/dummy/Omy-049
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCGGATTGCTGCAGG data/dummy/Omy-050
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAGATCTGTGCAGG data/dummy/Omy-051
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACAGCAGATGCAGG data/dummy/Omy-052
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAAGACTATGCAGG data/dummy/Omy-053
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCTCAATGATGCAGG data/dummy/Omy-054
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGGTGCGAATGCAGG data/dummy/Omy-055
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTGGTGGTATGCAGG data/dummy/Omy-056
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGGCTAACTGCAGG data/dummy/Omy-057
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCTAAGGTCTGCAGG data/dummy/Omy-058
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGATGCCTAATGCAGG data/dummy/Omy-059
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACCTCCAATGCAGG data/dummy/Omy-060
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAATGGAATGCAGG data/dummy/Omy-061
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCTGAGCCATGCAGG data/dummy/Omy-062
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGTACGCAATGCAGG data/dummy/Omy-063
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTTCACGCATGCAGG data/dummy/Omy-064
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGATAGCGACTGCAGG data/dummy/Omy-065
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGAACAGGCTGCAGG data/dummy/Omy-066
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAACGAACGTGCAGG data/dummy/Omy-067
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACGCTCGATGCAGG data/dummy/Omy-068
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCACTTCGATGCAGG data/dummy/Omy-069
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCTGGCATATGCAGG data/dummy/Omy-070
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGTCGTAGATGCAGG data/dummy/Omy-071
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACACGAGATGCAGG data/dummy/Omy-072
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACGACAAGTGCAGG data/dummy/Omy-073
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGACAGTGCTGCAGG data/dummy/Omy-074
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGTACAAGTGCAGG data/dummy/Omy-075
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACGTATCATGCAGG data/dummy/Omy-076
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAGCGTTATGCAGG data/dummy/Omy-077
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGAATCTGATGCAGG data/dummy/Omy-078
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGTCTGTCATGCAGG data/dummy/Omy-079
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAAGAGATCTGCAGG data/dummy/Omy-080
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGATTGGCTCTGCAGG data/dummy/Omy-081
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGAGTTAGCTGCAGG data/dummy/Omy-082
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCATCAAGTTGCAGG data/dummy/Omy-083
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGACTATGCATGCAGG data/dummy/Omy-084
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCATACCAATGCAGG data/dummy/Omy-085
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGACTAGTATGCAGG data/dummy/Omy-086
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGTGTTCTATGCAGG data/dummy/Omy-087
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAAGGACACTGCAGG data/dummy/Omy-088
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCAAGGAGCTGCAGG data/dummy/Omy-089
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGATGAATCTGCAGG data/dummy/Omy-090
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGTGGTCATGCAGG data/dummy/Omy-091
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAGAGTCAATGCAGG data/dummy/Omy-092
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCCAGTTCATGCAGG data/dummy/Omy-093
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGAGCTGAATGCAGG data/dummy/Omy-094
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGTAGGATGATGCAGG data/dummy/Omy-095
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGAATCCGTCTGCAGG data/dummy/Omy-096
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGCACCTTACTGCAGG data/dummy/Omy-097
 BarcodeSplitListBestRadPairedEnd.pl data/combined/LibPlate10-combined-R1.fastq data/combined/LibPlate10-combined-R2.fastq GGGCCAAGACTGCAGG data/dummy/Omy-098
