---
title: "Pop Gen"
author: "Alana Luzzio"
date: "2023-05-04"
output: html_document
---


```{r setup, include=FALSE}
#Setup to not print out excessive information
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

Read in libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggplot2)
library(ggforce)
library(dplyr)
library(plotrix)
library(plotly)
```

```{r}
# pca covMatrix 
mat <- as.matrix(read.table("cov/allwwhLCT.bamlist.PCA415.covMat"))

#metadata 
meta <- read_csv("meta/allwwhLCT.bamlist.csv")

# preparing the matrix for plotting , the parameters' name are generic for any covMat file
eig <- eigen(mat, symm=T)
eig$val <- eig$val/sum(eig$val)
PC <- as.data.frame(eig$vectors)
colnames(PC) <- gsub("V", "PC", colnames(PC))

var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)
```
#+ xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = "")) + ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = "")) 

```{r}
#adding metadata parameters
#PC$Location <- factor(meta$Location)
PC$Group <- factor(meta$Group, levels=c("LCT","RBT","REDBT","YCT"))
PC$Watershed <- factor(meta$Watershed_basin, levels = c("Willow Creek", "Little Whitehorse Creek", "Whitehorse Creek","Cottonwood Creek","willow whitehorse basin"))
  
#"MARLAKE", "DGVY_BOTT","TRUCKEE","WALK_BYDYS", "WALK_BYDYC", "WALK_BYDYCM","WALK_LWC","WALK_MCT","WALK_OhCanyon","WALK_UWC","WALK_SKD","WALK_SLV","KNG_WFCC","STN_DCAC","WALK_WLF", "WALK_MILL","ONR_OharrelCreek","WALK_ByDay","WALK_Silver","WALK_Murphy","WALK_SJR"))

#"Mason Valley Hatchery", "Trelease Creek", "Bottom", "Rock Park", "Verdi Dam", "Derby Dam", "McCarren Ranch", "Riverbend", "Patagonia", "Wingfield_Downtown", "Heenan Lake", "East Fork", "East Fork Golden Canyon Creek", "East Fork Murray Canyon Creek", "East Fork Poison Flat Creek", "Independence Lake", "North Fork Pacific Creek", "North Fork Marshall Canyon Creek", "Oharrel Creek", "Pole Creek", "Upper Truckee", "North Fork Milk Ranch Creek", "Macklin Creek"))
  
#"WALK_BYDYS", "WALK_BYDYC", "WALK_BYDYCM","WALK_LWC","WALK_MCT","WALK_OhCanyon","WALK_UWC","WALK_SKD","WALK_SLV","KNG_WFCC","STN_DCAC","WALK_WLF", "WALK_MILL","ONR_OharrelCreek","WALK_ByDay","WALK_Silver","WALK_Murphy","WALK_SJR"))
  
#"CAR_HL","CAR_EF", "CAR_EFGCC", "CAR_EFMCC", "CAR_EFPFC", "IPL_IPL", "MOK_NFPC", "MOK_NFMCC", "ONR_OHC", "TKR_PC", "TKR_UP", "MOK_NFMRC", "YUB_MC"))
  
#"Heenan Lake", "East Fork", "East Fork Golden Canyon Creek", "East Fork Murray Canyon Creek", "East Fork Poison Flat Creek", "Independence Lake", "North Fork Pacific Creek", "North Fork Marshall Canyon Creek", "Oharrel Creek", "Pole Creek", "Upper", "North Fork Milk Ranch Creek", "Macklin Creek"))
  
#"Mason Valley Hatchery", "Trelease Creek", "Bottom", "Rock Park", "Verdi Dam", "Derby Dam", "McCarren Ranch", "Riverbend", "Patagonia", "Wingfield_Downtown", "EastCreek", "SeventySix", "EightMile", "IndianCreek", "LamoilleCreek", "SunCreek", "WillowCreek", "Heenan Lake", "East Fork", "East Fork Golden Canyon Creek", "East Fork Murray Canyon Creek", "East Fork Poison Flat Creek", "Independence Lake", "North Fork Pacific Creek", "North Fork Marshall Canyon Creek", "Oharrel Creek", "Pole Creek", "Upper Truckee", "North Fork Milk Ranch Creek", "Macklin Creek"))
                                                        
#Mason Valley Hatchery", "Trelease Creek", "Bottom", "Rock Park", "Verdi Dam", "Derby Dam", "McCarren Ranch", "Riverbend", "Patagonia", "Wingfield_Downtown", "EastCreek", "SeventySix", "EightMile", "IndianCreek", "LamoilleCreek", "SunCreek", "WillowCreek"))
                                                                
#"Heenan Lake", "East Fork", "East Fork Golden Canyon Creek", "East Fork Murray Canyon Creek", "East Fork Poison Flat Creek", "Independence Lake", "North Fork Pacific Creek", "North Fork Marshall Canyon Creek", "Oharrel Creek", "Pole Creek", "Upper Truckee", "North Fork Milk Ranch Creek", "Macklin Creek"))

#"DGVY", "INC", "THD", "TWLV", "TRURIV", "CAR_HL", "CAR", "IPL", "MOK", "ONR", "TKR", "YUB", "BYDY", "WLF", "MILL", "MCT", "OHC", "SKD", "SLV", "KNG", "STN", "SJR")) # if you like to order populations do this 

# color palette manually
cbPalette3 <- c( "#009E73","#F0E442", "#56B4E9", "#0072B2",
                 "#FFCD5D",  "#AAC6C2","#EB9B68", "#ad9d20", "#388e8c", "#97113a","#f072ef", "#ff3c0e",
                 "#e700bb", "#00bbe7", "#a6ff34",  "#CC79A7","#2c00e7","#D55E00", 
                 "#2fbcd0", "#C7B9C2", "#913e96", "#cc0000",
                 "#F0E442","#009E73",  "#BAE600", "#7FE5E5",
                 "#e62c00",  "#009a1d" ,  "#7f5800", "#946600" )



p3 <- ggplot(data=PC, aes(x=PC1, y=PC2, fill=Watershed, shape=Group)) + 
   theme_classic() + 
  geom_point(size=4, alpha=0.7) + 
  labs(title=paste0("Willow Whitehorse Basin LCT")) +
  xlab(paste0("PC1 ", round(eig$val[1]*100,2), "%")) +
  ylab(paste0("PC2 ", round(eig$val[2]*100,2), "%")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(override.aes=list(shape=c(22)))) +
  # adjusting legend
  theme(#legend.justification = c("right", "bottom"),
    #    legend.key = element_rect(),
     #   legend.position = "top",
    #    legend.box.just = "top",
     #   legend.margin = margin(0, 0, 0, 0),
     #   legend.direction = "horizontal",
        plot.title =  element_text(size=14, face="bold"),
        legend.text = element_text(size = 8, face= "bold"),
        legend.title = element_text(colour="black", size=10, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA, size=1)) +
  scale_fill_manual(values=cbPalette3)

p3
#ggplotly(p3)

ggsave("outputs/101/wwh.pdf")
```

